### ISSUE TITLE
如果需要加上搜索到的时间和搜索到的摘要该怎么样？试了半天没试出来，跪求帮忙！

### ISSUE THREAD

**Issue by kaysar01** [Evilran/baidusearch_spider#1]
是直接在try函数下加一个abstract吗？还是说要重新在下面写一个try函数，可是我怎么改都不能成功，求帮忙！！！

**Comment by Evilran** [comment]
已添加此功能，请拉取最新代码。

---
Commit: https://github.com/Evilran/baidusearch_spider/commit/36d175034f9153f5ed3bdbc671ce89677f5d5ed4

**Comment by kaysar01** [comment]
不好意思，我没有表达正确我的意图，我是想要获取搜索结果中的发表时间和搜索出来的摘要，通过您帮忙改进的代码还是没能成功获取，不知道能不能还求您帮忙？我也尝试了很多次修改，可是还是不能，实在是着急，不过还是感谢您的帮忙
![InkedQQ图片20220224173505](https://user-images.githubusercontent.com/54786212/155498686-fdf7fa6b-5598-4b5e-8c4b-6520ee34d275.jpg)
是这张照片中的时间和摘要，都能在标签中查询到，可是我小白，经过了很多次尝试还是没能成功获取，希望您能帮帮忙！
