### ISSUE TITLE
大佬，我不知道该怎么添加代理了，可以帮帮忙嘛？

### ISSUE THREAD

**Issue by kaysar01** [Evilran/baidusearch_spider#3]
需要抓取的数据比较多，现在不知道该怎么调价代理IP了，跟据百度学了很多，最终要么就是直接什么都用不了，要么就是解析失败

**Comment by Evilran** [comment]
建议用一些免费代理池，比如 socks5 或者 http 代理，然后在 requests 的请求中加入代理池轮切。

```python
import requests 
proxies = { "http": "http://127.0.0.1:8080", "https": "socks5://127.0.0.1:7889"} 
requests.get("https://evilran.me", proxies=proxies)
```
---
Reference: [利用fofa搜索socks5开放代理进行代理池轮切的工具](https://github.com/akkuman/rotateproxy)

**Comment by kaysar01** [comment]
好嘞，谢谢啦
